name: Deploy to Surge

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge.sh
      run: npm install --global surge

    - name: Deploy to Surge.sh
      run: |
        surge token ${{ secrets.SURGE_TOKEN }}
        surge --project ./ --domain Practica.surge.sh
