name: Deploy to Surge

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge.sh
      run: npm install --global surge

    - name: Deploy to Surge.sh
      run: |
        surge token 9e3245c4523779c03a01ac588e5a7f1a
        surge --project ./ --domain Practica2.surge.sh
